try again

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -44,7 +44,7 @@ jobs:
       - name: Use base env file if it was changed
         run: |
           git fetch origin main
-          if git diff --name-only origin/main | grep -E '(${{env.BASE_ENV }}|.*lock.yaml)$'; then
+          if git diff --name-only origin/main | grep -E '(${{ env.BASE_ENV }}|.*lock.yaml)$'; then
             if git diff --name-only origin/main | grep -E '.*lock.yaml'; then
               echo "Lock files changed. Using lock files."
               echo "env_file=${{ matrix.env_file }}" >> $GITHUB_ENV
@@ -73,7 +73,7 @@ jobs:
 
       - name: Update environment
         if: steps.cache-env.outputs.cache-hit != 'true'
-        run: conda env update -n pypsa-earth -f ${{ matrix.env_file }}
+        run: conda env update -n pypsa-earth -f ${{ env.env_file }}
 
       - name: Conda list
         run: conda list
@@ -120,109 +120,108 @@ jobs:
 
       - name: Extract objective
         id: extract_obj
-        run: |2
+        run: |
+          shopt -s nullglob
 
-        shopt -s nullglob
+          OBJ_STRING="(?<=INFO:__main__:Objective function: ).*"
+          LOG_FILES=(./logs/solve_network/*_python.log ./logs/*/solve_network/*_python.log)
+          echo "Extracting the objective values from the logs"
+          echo "Solver log files: $LOG_FILES"
+          OBJ_FOUND=$(
+            awk '/INFO:__main__:Objective function: /{
+                   sub(/\r$/, "");
+                   sub(/.*INFO:__main__:Objective function: /, "");
+                   print FILENAME ":" $0
+                 }' "${LOG_FILES[@]}" || true
+          )
 
-        OBJ_STRING="(?<=INFO:__main__:Objective function: ).*"
-        LOG_FILES=(./logs/solve_network/*_python.log ./logs/*/solve_network/*_python.log)
-        echo "Extracting the objective values from the logs"
-        echo "Solver log files: $LOG_FILES"
-        OBJ_FOUND=$(
-          awk '/INFO:__main__:Objective function: /{
-                 sub(/\r$/, "");
-                 sub(/.*INFO:__main__:Objective function: /, "");
-                 print FILENAME ":" $0
-               }' "${LOG_FILES[@]}" || true
-        )
+          shopt -u nullglob
 
-        shopt -u nullglob
-
-        # The objective can be also empty (in case some tests failed)
-        if [ -z "$OBJ_FOUND" ]; then
-          echo "Objective not found."
-          exit 1
-        else
-          echo "Objective value found: $OBJ_FOUND"
-          echo "Writing to GitHub output"
-          #printf "%s\n" "obj_match=$OBJ_FOUND" >> "$GITHUB_OUTPUT"
-          delim="OBJ_EOF_$(date +%s%N)"
-          {
-            echo "obj_match<<$delim"
-            printf '%s\n' "$OBJ_FOUND"
-            echo "$delim"
-          } >> "$GITHUB_OUTPUT"
-        fi
-
-        echo "The objective extracted successfully"
-
-        # Add Python import
-        extract_obj_for_path_py() {
-          python - "$1" "$2" <<'PY'
-        import sys
-        from test.utils.extract_ref_objective import extract_obj_for_path
-        dir, fl = sys.argv[1], sys.argv[2]
-        print(extract_obj_for_path(dir, fl))
-        PY
-        }
-
-        # Create properly formatted outputs
-        clean_csv_cell() {
-          local s=$1
-          # Add quotes if the field contains a delimiter or a new string
-          if [[ "$s" == *\"* || "$s" == *,* || "$s" == *$'\n'* || "$s" == *$'\r'* || "$s" == " "* || "$s" == *" " ]]; then
-            # Escape embedded quotes by doubling them
-            s=${s//\"/\"\"}
-            printf '"%s"' "$s"
+          # The objective can be also empty (in case some tests failed)
+          if [ -z "$OBJ_FOUND" ]; then
+            echo "Objective not found."
+            exit 1
           else
-            printf '%s' "$s"
-          fi
-        }
-
-        # Table is used as a visual part in Actions Summary
-        TABLE="| Folder | File | Current Objective | Reference Objective |"
-        TABLE+="\n|:----|:-----|------------------:|--------------------:|"
-
-        # Generation of csv files facilitates objective update
-        CSV_FILE="ref_objectives-${{ matrix.os }}.csv"
-        CSV_CONTENT="folder,file,objective"
-
-        while IFS= read -r line; do
-          FILE=$(echo "$line" | cut -d: -f1)
-          VALUE=$(echo "$line" | cut -d: -f2-)
-          BASENAME=$(basename "$FILE")
-
-          # An enclosing folder contains a name of the run
-          FOLDER=$(echo "$FILE" | sed -E 's|.*/logs/([^/]+)/solve_network/.*|\1|')
-
-          if [[ "$FILE" == ./logs/solve_network/* ]]; then
-            FOLDER="default"
+            echo "Objective value found: $OBJ_FOUND"
+            echo "Writing to GitHub output"
+            #printf "%s\n" "obj_match=$OBJ_FOUND" >> "$GITHUB_OUTPUT"
+            delim="OBJ_EOF_$(date +%s%N)"
+            {
+              echo "obj_match<<$delim"
+              printf '%s\n' "$OBJ_FOUND"
+              echo "$delim"
+            } >> "$GITHUB_OUTPUT"
           fi
 
-          VALUE_RAW=$(awk -v v="$VALUE" 'BEGIN { printf "%.2f\n", v }')
-          OBJ_SCALE=1000000
-          VALUE_SCALED=$(awk -v v="$VALUE" -v s="$OBJ_SCALE" 'BEGIN { if (s==0) { print "NaN"; exit 1 } printf "%.2f\n", v/s }')
+          echo "The objective extracted successfully"
 
-          REF_VALUE=$(extract_obj_for_path_py "$FOLDER" "$BASENAME")
+          # Add Python import
+          extract_obj_for_path_py() {
+            python - "$1" "$2" <<'PY'
+          import sys
+          from test.utils.extract_ref_objective import extract_obj_for_path
+          dir, fl = sys.argv[1], sys.argv[2]
+          print(extract_obj_for_path(dir, fl))
+          PY
+          }
 
-          TABLE+="\n| $FOLDER | $BASENAME | \`$VALUE_SCALED\` | \`$REF_VALUE\` |"
-          CSV_CONTENT+=$'\n'"$(clean_csv_cell $FOLDER),$(clean_csv_cell $BASENAME),$(clean_csv_cell $VALUE_RAW)"
+          # Create properly formatted outputs
+          clean_csv_cell() {
+            local s=$1
+            # Add quotes if the field contains a delimiter or a new string
+            if [[ "$s" == *\"* || "$s" == *,* || "$s" == *$'\n'* || "$s" == *$'\r'* || "$s" == " "* || "$s" == *" " ]]; then
+              # Escape embedded quotes by doubling them
+              s=${s//\"/\"\"}
+              printf '"%s"' "$s"
+            else
+              printf '%s' "$s"
+            fi
+          }
 
-        done <<< "$OBJ_FOUND"
+          # Table is used as a visual part in Actions Summary
+          TABLE="| Folder | File | Current Objective | Reference Objective |"
+          TABLE+="\n|:----|:-----|------------------:|--------------------:|"
 
-        echo -e "$TABLE"
+          # Generation of csv files facilitates objective update
+          CSV_FILE="ref_objectives-${{ matrix.os }}.csv"
+          CSV_CONTENT="folder,file,objective"
 
-        echo "The output table is formed"
+          while IFS= read -r line; do
+            FILE=$(echo "$line" | cut -d: -f1)
+            VALUE=$(echo "$line" | cut -d: -f2-)
+            BASENAME=$(basename "$FILE")
 
-        echo "### Objective Results of CI Run" >> "$GITHUB_STEP_SUMMARY"
+            # An enclosing folder contains a name of the run
+            FOLDER=$(echo "$FILE" | sed -E 's|.*/logs/([^/]+)/solve_network/.*|\1|')
 
-        echo "GITHUB_STEP_SUMMARY successfully supplemented with a header"
+            if [[ "$FILE" == ./logs/solve_network/* ]]; then
+              FOLDER="default"
+            fi
 
-        printf "%b\n" "$TABLE" >> "$GITHUB_STEP_SUMMARY"
+            VALUE_RAW=$(awk -v v="$VALUE" 'BEGIN { printf "%.2f\n", v }')
+            OBJ_SCALE=1000000
+            VALUE_SCALED=$(awk -v v="$VALUE" -v s="$OBJ_SCALE" 'BEGIN { if (s==0) { print "NaN"; exit 1 } printf "%.2f\n", v/s }')
 
-        printf "%b" "$CSV_CONTENT" > "$CSV_FILE"
+            REF_VALUE=$(extract_obj_for_path_py "$FOLDER" "$BASENAME")
 
-        echo "Objective values uploaded to csv"
+            TABLE+="\n| $FOLDER | $BASENAME | \`$VALUE_SCALED\` | \`$REF_VALUE\` |"
+            CSV_CONTENT+=$'\n'"$(clean_csv_cell $FOLDER),$(clean_csv_cell $BASENAME),$(clean_csv_cell $VALUE_RAW)"
+
+          done <<< "$OBJ_FOUND"
+
+          echo -e "$TABLE"
+
+          echo "The output table is formed"
+
+          echo "### Objective Results of CI Run" >> "$GITHUB_STEP_SUMMARY"
+
+          echo "GITHUB_STEP_SUMMARY successfully supplemented with a header"
+
+          printf "%b\n" "$TABLE" >> "$GITHUB_STEP_SUMMARY"
+
+          printf "%b" "$CSV_CONTENT" > "$CSV_FILE"
+
+          echo "Objective values uploaded to csv"
 
       - name: Upload csv artifacts
         uses: actions/upload-artifact@v7
